version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 4001:80   #zewnetrzny 4001
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html       #pliki php/html(przekazanie sciezki do php-fpm)
    networks:
      - frontend    #internet
      - backend   #komunikacja z php 
    depends_on:
      - php       #czeka na uruchomienie php

  php:
    image: php:8.2-fpm-alpine
    container_name: php
    volumes:
      - ./www:/var/www/html     #wspoldzielone pliki nginx
    networks:
      - backend     #wewnetrzna komunikacja
    environment:
      - PHP_FPM_LISTEN=9000       #port nasluchiwania


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword           #hasło dla roota
      MYSQL_DATABASE: testdb    #automatycznie tworzona baza testdb
      MYSQL_USER: testuser        #nowy uzytkownik 
      MYSQL_PASSWORD: testpassword      #haslo nowego uzytkownika
    volumes:
      - mysql_data:/var/lib/mysql       #pechowywanie danych (wolumen), sciezka wewnatrz kontnera gdzie mysql trzyma dane
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql     #polaczenie z baza mysql
      PMA_PORT: 3306      #port mysql
      MYSQL_ROOT_PASSWORD: rootpassword       #haslo
    networks:
      - frontend      #dostep z przegladarki
      - backend       #polaczenie z mysql
    depends_on:
      - mysql       #czeka na mysql

volumes:
  mysql_data:

#definicja sieci
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
