version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 4001:80   #zewnetrzny 4001
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html       #pliki php/html
    networks:
      - frontend    #internet
      - backend   #komunikacja z php 
    depends_on:
      - php

  php:
    image: php:8.2-fpm-alpine
    container_name: php
    volumes:
      - ./www:/var/www/html     #wspoldzielone pliki nginx
    networks:
      - backend     #wewnetrzna komunikacja
    environment:
      - PHP_FPM_LISTEN=9000


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb    #automatycznie tworzona baza 
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql     #polaczenie z baza mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - frontend      #dostep z przegladarki
      - backend       #polaczenie z mysql
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
